version: '3.6'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672' #The standard AMQP protocol port
      - '15672:15672' #HTTP management UI
    environment:
      AMQP_URL: 'amqp;//rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: rabbitmqctl status || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 40s
  orden:
    build: 
      context: orden
    ports:
      - "5005:5005"
  consumidor-orden:
    build: 
      context: orden
    command: "python consumer.py"
    depends_on:
      rabbitmq:
        condition: service_healthy
  plan-ruta-1:
    build:
      context: plan-ruta-1
  plan-ruta-2:
    build: 
      context: plan-ruta-2
  plan-ruta-3:
    build: 
      context: plan-ruta-3
  voting:
    build: 
      context: voting
  monitor:
    build: 
      context: monitor
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - plan-ruta-1
      - plan-ruta-2
      - plan-ruta-3
      - voting
      - monitor
    ports:
      - "8080:8080"


