version: '3.6'

services:
  orden:
    build: 
      context: orden
    ports:
      - "5005:5005"
  plan-ruta-1:
    build: 
      context: plan-ruta-1
  plan-ruta-2:
    build: 
      context: plan-ruta-2
  plan-ruta-3:
    build: 
      context: plan-ruta-3
  voting:
    build: 
      context: voting
  monitor:
    build: 
      context: monitor
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orden
      - plan-ruta-1
      - plan-ruta-2
      - plan-ruta-3
      - voting
      - monitor
    ports:
      - "8080:8080"


