version: '3.6'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672' #The standard AMQP protocol port
      - '15672:15672' #HTTP management UI
    environment:
      AMQP_URL: 'amqp;//rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: rabbitmqctl status || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 40s
  orden:
    build: 
      context: orden
  cola-mensajeria:
    build: 
      context: cola-mensajeria
    command: "python cola-entrada.py"
    depends_on:
      rabbitmq:
        condition: service_healthy
  consumer-orden:
    build: 
      context: orden
    command: "python consumer.py"
    depends_on:
      rabbitmq:
        condition: service_healthy
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orden
      - cola-mensajeria
      - consumer-orden
    ports:
      - "8080:8080"
